### PR TITLE
Depending on viewport, borders dont show up

### PR DESCRIPTION
**Pull request by kevinhofmaenner**
https://github.com/richardtallent/vue-simple-calendar/issues/13

### CODE REVIEW

**Comment by richardtallent** [comment]
Hmm... ok, now that I'm looking at the code tonight, I'm confused.

I'm aware of an issue where the left or bottom border of the *entire* calendar month (and a similar issue with the day names row) can disappear in Chrome/OSX (which I use) for very specific widths--the border calculation itself is always at least 1px, but the week/day element positioning is occasionally rounded wrong and they hide the border rather than being inside of it. I haven't found a solution other than a 1px border so far, which I've been avoiding. I've been meaning to see if switching to content-box (ugh) would do the trick.

But the patch above is adjusting the borders for *event overlays*, not the month/week/day elements, and I haven't seen any issues with the event borders or in the screen shot provided. Can you clarify what you're seeing?

If there's a problem with event borders that I'm not able to reproduce, I'm fine with this change, but since nested calc() only recently (within the past year or so?) made it in as a clarification in the CSS spec, I'd have to check IE11 first to ensure it renders properly, since I want to maintain support for it.

**Comment by houseoftech** [comment]
@richardtallent Why not use 1px border?

**Comment by richardtallent** [comment]
Everything else is using em-based measurements.

But I don’t think it would actually resolve the issue — the border is being rendered, but the week/day element top/left positions are rounded incorrectly at some sizes and occluding the parent border.

I’ve been mulling the idea of using content-box sizing on the parent, but haven’t tried it yet.

**Comment by richardtallent** [comment]
After attempting changes to box-sizing, I reluctantly moved the `month` and `dayList` borders to use `1px` to ensure that the borders show up at all sizes on Chrome.

**Pull request closed without merging**
