### PR TITLE
Adding in the props for scoped slots on the header

### PR DESCRIPTION
**Pull request by scottt2**
Love the library! I didn't see a contributors portion of the readme, so definitely lemme know if I am not doing something the way you would prefer.

Basically this PR is to just add props on the `header` slot such that we can have access to them to further customize the look and feel.

Thanks!
-Tyler

### CODE REVIEW

**Comment by scottt2** [comment]
Thanks for the thoughtful reply! Yeah, honestly I felt a bit dirty doing it that way. I am totally open to a different way.

The use case I’d like to solve is being able to layout the header with a custom button layout and have them respond with the same event handlers that the default slot content. 

-Tyler

**Comment by richardtallent** [comment]
I'm trying to release 2.2.0 soon, but I'll be working on 3.0.0 immediately afterward (within a few weeks), which should address the header slot logic issues you brought up here, along with re-vamping of the CSS. Not much else will be in 3.0.

**Comment by scottt2** [comment]
@richardtallent Thanks, man! Is there anything in terms of the 3.0 that you need help with?

**Comment by richardtallent** [comment]
Thanks for offering! I think the top issues right now are:
- Restoring IE11 compatibility (I'd like to do a point release 2.2.1 for that)
- Removing webpack config dross no longer needed with webpack 4, especially in the sample app
- Mobile/tablet-compatible drag and drop of events, ideally w/o adding a dependency (but it may be needed, I think I recall that mobile drag/drop is more complicated).

With those three issues resolved, the rest of 3.0 can be focused on better header slots and better CSS theming.

**Comment by richardtallent** [comment]
Thanks again, Scott! Version 3.0 is about to be published, and I figured out a decent way to deal with slotted custom headers. Please let me know what you think!

**Pull request closed without merging**
