### PR TITLE
Added support for custom inline CSS to be passed through

### PR DESCRIPTION
**Pull request by apalethorpe**

### CODE REVIEW

**Comment by richardtallent** [comment]
Thanks for the request!

Two thoughts:

1. I think rather than `css`, we should use `style`.

2. What is the use case for a style-level override? The `event` structure already supports adding `classes`, and past a certain point, passing rendering details inside props starts to feel like a code smell (versus, say, just using a slot). Doesn't mean we can't add this, I'm just trying to figure out what sort of problem requires an event to carry such low-level information about how it is to be rendered, and if that is encouraging a poor separation of content and output.

**Comment by apalethorpe** [comment]
This might be a bit idiosyncratic on my part, but I'm developing an application that lets certain users put custom events on to a shared calendar and can dictate the background and text colours themselves. This means there isn't a class, just two colour hex values from my DB that I need to inject into the element's style somehow.

Prior to my suggested change, I was doing a rather hacky solution involving dynamically creating <style> tags and filling them with new css classes. I felt that passing the style directly to the event elements was a bit nicer.

**Comment by lochstar** [comment]
Can the users select any combination or is it a pre-set list? If pre-set, then you could define a series of classes to attach. Although I think being able to pass style directly in gives us more flexibility.

**Comment by richardtallent** [comment]
Pretty brave letting users pick a color! :) But yes, that does sound like a use case that would either require `style`, or a custom event `slot`, or *many* CSS classes.

Let's rename to `style` for consistency with the markup and update the docs and I'll be happy to merge.

**Comment by richardtallent** [comment]
I made the update to use `style`, updated the docs, and merged. Thanks!

This will end up in the 3.1 release, which I'm planning to do after migrating to vue-cli 3.0 (which is still in beta).

**Comment by apalethorpe** [comment]
@lochstar Users can select any colour they like. Didn't fancy having 32,000,000+ classes to cover the different possibilities ;-)

**Pull request merged**
