### PR TITLE
Change "click-date" event parameters into object which contains original JS event.

### PR DESCRIPTION
**Pull request by ShuyqcK**
Transform "click-date" event data's into an object wich contains the day, and the original JS event.

### CODE REVIEW

**Comment by iamfrank** [comment]
I approve of this PR. This would make it much easier to create custom functionality for what happens when a date is clicked.

**Comment by richardtallent** [comment]
I agree, @iamfrank, looks like a good enhancement. Since it's a breaking API change, however, it would require a major version number change for a fairly minor tweak. So, I'd like to think about the timing and see if there are some other items that can be handled at the same time to minimize major semver jumps.

**Comment by richardtallent** [comment]
@ShuyqcK and @iamfrank, I just merged a PR from another user who asked for the original window event to be passed as a third parameter for `$emit()`. I think that approach works better than passing an object in the second parameter, as it isn't a breaking change. We should consider standardizing on this so the emitted events have similar signatures.

**Comment by richardtallent** [comment]
Closing this since we came up with a non-breaking solution.

**Pull request closed without merging**
